### PR TITLE
[FIX] Add tags and ids to updated firewall

### PR DESCRIPTION
**Pull request by yringler**
I'm trying this out now, if it works I'll remove this from draft status

### CODE REVIEW

**Comment by yringler** [comment]
At first it didn't work; that's when I noticed the dist folder in the repo.
But before I did that, I made some other changes.
One (using ... spread) I'll keep, the logging I'll remove

**Comment by patoroco** [comment]
Hi @yringler , thanks for your collaboration!

Could you explain to me how to check that everything is working as expected? It would be nice to have a test on this PR, though.

**Comment by yringler** [comment]
Yes, I love tests, but somehow I never get around to writing them... and IDK how to write a test for this.
But for manual checking - have you been able to replicate #7 ?

Here's how I confirmed that this PR fixes the issue:
1. Apply firewall to droplet
2. Use this action on that firewall
3. Check that the firewall is still applied to droplet

In general, it's a reasonable change - when updating, we want everything to be the same, except for the one IP address.
So it's reasonable to use the spread operator.
Of course, I've been in this game for a while, and if I had to bet a nickle every time I said that I'd probably be broke by now 😏 . But be that as it may

Like @basmilius wrote there,
> The request body when updating a firewall should contain droplet_ids and tags.

**Comment by patoroco** [comment]
I've just refreshed the branch and I'm going to merge this PR. Thanks for your collaboration, @yringler!

**Comment by yringler** [comment]
You're very welcome! It'll be nice to move my pipeline back to using your repo.

**Pull request merged**
